### ISSUE TITLE
Build error : non-constant-expression cannot be narrowed from type 'int' to 'unsigned int' in initializer list [-Wc++11-narrowing]

### ISSUE THREAD

**Issue by mdogancay** [LiangliangNan/Easy3D#128] opened 2022-08-04 09:31 UTC
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
cmake version 3.23.2

Error info :
```
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:969:33: error: non-constant-expression cannot be narrowed from type 'unsigned long' to 'unsigned int' in initializer list [-Wc++11-narrowing]
        unsigned int edgesExtent[] = { uextent + 1, vextent + 1, 3, 3 };
                                       ^~~~~~~~~~~
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:969:33: note: insert an explicit cast to silence this issue
        unsigned int edgesExtent[] = { uextent + 1, vextent + 1, 3, 3 };
                                       ^~~~~~~~~~~
                                       static_cast<unsigned int>( )
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:969:46: error: non-constant-expression cannot be narrowed from type 'unsigned long' to 'unsigned int' in initializer list [-Wc++11-narrowing]
        unsigned int edgesExtent[] = { uextent + 1, vextent + 1, 3, 3 };
                                                    ^~~~~~~~~~~
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:969:46: note: insert an explicit cast to silence this issue
        unsigned int edgesExtent[] = { uextent + 1, vextent + 1, 3, 3 };
                                                    ^~~~~~~~~~~
                                                    static_cast<unsigned int>( )
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1014:33: error: non-constant-expression cannot be narrowed from type 'int' to 'unsigned int' in initializer list [-Wc++11-narrowing]
                        unsigned int edgeIndex[] = { x, y, 1, 2 };
                                                     ^
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1014:33: note: insert an explicit cast to silence this issue
                        unsigned int edgeIndex[] = { x, y, 1, 2 };
                                                     ^
                                                     static_cast<unsigned int>( )
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1014:36: error: non-constant-expression cannot be narrowed from type 'int' to 'unsigned int' in initializer list [-Wc++11-narrowing]
                        unsigned int edgeIndex[] = { x, y, 1, 2 };
                                                        ^
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1014:36: note: insert an explicit cast to silence this issue
                        unsigned int edgeIndex[] = { x, y, 1, 2 };
                                                        ^
                                                        static_cast<unsigned int>( )
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1027:33: error: non-constant-expression cannot be narrowed from type 'int' to 'unsigned int' in initializer list [-Wc++11-narrowing]
                        unsigned int edgeIndex[] = { x + 1, y, 0, 1 };
                                                     ^~~~~
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1027:33: note: insert an explicit cast to silence this issue
                        unsigned int edgeIndex[] = { x + 1, y, 0, 1 };
                                                     ^~~~~
                                                     static_cast<unsigned int>( )
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1027:40: error: non-constant-expression cannot be narrowed from type 'int' to 'unsigned int' in initializer list [-Wc++11-narrowing]
                        unsigned int edgeIndex[] = { x + 1, y, 0, 1 };
                                                            ^
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1027:40: note: insert an explicit cast to silence this issue
                        unsigned int edgeIndex[] = { x + 1, y, 0, 1 };
                                                            ^
                                                            static_cast<unsigned int>( )
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1043:33: error: non-constant-expression cannot be narrowed from type 'int' to 'unsigned int' in initializer list [-Wc++11-narrowing]
                        unsigned int edgeIndex[] = { x + 1, y + 1, 0, 1 };
                                                     ^~~~~
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1043:33: note: insert an explicit cast to silence this issue
                        unsigned int edgeIndex[] = { x + 1, y + 1, 0, 1 };
                                                     ^~~~~
                                                     static_cast<unsigned int>( )
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1043:40: error: non-constant-expression cannot be narrowed from type 'int' to 'unsigned int' in initializer list [-Wc++11-narrowing]
                        unsigned int edgeIndex[] = { x + 1, y + 1, 0, 1 };
                                                            ^~~~~
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1043:40: note: insert an explicit cast to silence this issue
                        unsigned int edgeIndex[] = { x + 1, y + 1, 0, 1 };
                                                            ^~~~~
                                                            static_cast<unsigned int>( )
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1059:33: error: non-constant-expression cannot be narrowed from type 'int' to 'unsigned int' in initializer list [-Wc++11-narrowing]
                        unsigned int edgeIndex[] = { x + 1, y + 1, 1, 0 };
                                                     ^~~~~
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1059:33: note: insert an explicit cast to silence this issue
                        unsigned int edgeIndex[] = { x + 1, y + 1, 1, 0 };
                                                     ^~~~~
                                                     static_cast<unsigned int>( )
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1059:40: error: non-constant-expression cannot be narrowed from type 'int' to 'unsigned int' in initializer list [-Wc++11-narrowing]
                        unsigned int edgeIndex[] = { x + 1, y + 1, 1, 0 };
                                                            ^~~~~
/project/p/3d/cpp/Easy3D/3rd_party/ransac/Bitmap.cpp:1059:40: note: insert an explicit cast to silence this issue
                        unsigned int edgeIndex[] = { x + 1, y + 1, 1, 0 };
                                                            ^~~~~
                                                            static_cast<unsigned int>( )
10 errors generated.
make[2]: *** [3rd_party/ransac/CMakeFiles/3rd_ransac.dir/build.make:76: 3rd_party/ransac/CMakeFiles/3rd_ransac.dir/Bitmap.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1485: 3rd_party/ransac/CMakeFiles/3rd_ransac.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```

Any help ?

**Comment by LiangliangNan** [comment] 2022-08-19 15:14
This is weird. I just tested on ubuntu 20.04 with GCC 7, 8, 9, 10, and 11. All passed.
See here:
https://github.com/LiangliangNan/Easy3D/actions/runs/2890265663

Did you make any changes to the code?

**Comment by mdogancay** [comment] 2022-08-23 08:16
> 

No

**Comment by LiangliangNan** [comment] 2022-08-23 08:59
I couldn't reproduce the issue since I don't have exactly the same environment as yours. There is not such an issue with the other versions of GCC.
A workaround is to avoid the type conversion or to explicitly convert the type from `int` to `unsigned int` by surrounding the variables with `static_cast<unsigned int>( )`. 
I've made such a change and code in the `dev` branch. Can you give it a try and let me know if it solves the issue?

**Comment by mdogancay** [comment] 2022-08-23 10:33
> 

Thank you so much for help and fast reply. I'll try it on my available time. I'll share the results.

**Comment by LiangliangNan** [comment] 2022-09-06 06:50
I believe this issue has been solved, so I am going to close it.
Please feel free to reopen it if there is still the same/similar issue.

**Closed by LiangliangNan** 2022-09-06 06:50 UTC
