### ISSUE TITLE
[BUG] - dpi_scaling distorts multi viewports

### ISSUE THREAD

**Issue by CharlesJQuarra** [LiangliangNan/Easy3D#168] opened 2023-07-23 00:55 UTC
**Describe the bug**
Tutorial_205_Multiview looks distorted after zooming toward the spheres (See screenshot)

I debugged the easy3d/viewer/multi_viewer.cpp and inside the constructor the view_width is 400. However after update_division(), the viewports are rendered with effective width of 450. I realised that dpi_scaling() is returning 1.125 and that this factor seems to be the culprit, after I override this to 1.0 the distortion seems resolved

**Development/Running environment:**
 - OS: Linux Ubuntu 20.04

![Screenshot from 2023-07-22 19-45-38](https://github.com/LiangliangNan/Easy3D/assets/7565570/7abc1b7d-d277-4f5b-98f8-734a575d04a0)

**Comment by LiangliangNan** [comment] 2023-08-21 04:16
Hi, thanks for reporting this issue.
   “dpi_scaling() is returning 1.125” but the actual value is 1.0 – this is quite weird and suspicious.
Can you debug and go inside this function and see what width and height values are for the framebuffer?
(I cannot reproduce this issue, and it is apparently not correct to simply override the dpi factor to 1).

**Comment by LiangliangNan** [comment] 2023-09-14 19:05
I've tested it on Linux Ubuntu 22, and everything seems working fine. 
I am going to close this issue. Please feel free to reopen it when you can reproduce the issue.

**Closed by LiangliangNan** 2023-09-14 19:05 UTC
Labels: bug
